### ISSUE TITLE
Incremental training, incorporating small model(SC preface)

### ISSUE THREAD

**Issue by aj7tesh** [project-anuvaad/OpenNMT-py#18]

**Comment by aj7tesh** [comment]
incremental training using SC preface specific is put to training for a further of 30k steps over 100k model built earlier.

**Comment by aj7tesh** [comment]
Testest model on first checkpoint i.e 105k step. The model is overfit and not performing at all on normal sentences. This is possibly because for incremental training we used only the extra data (SC preface specific) and not old data+ new data.
Now, I will experiment with one more model where I will use all the data together and retrain the model from 100k step for next 30k, to see how does incremental training behaves in this case

**Comment by aj7tesh** [comment]
model 2 is trained and is being tested

**Comment by VivekRaghavan** [comment]
Any update on the results of this model ?

Vivek

**Comment by aj7tesh** [comment]
Working on that only. Will publish the result today

**Comment by aj7tesh** [comment]
Exp two is published on 11 september. More experiments need to be done
