### ISSUE TITLE
Constitutional Language pair model training

### ISSUE THREAD

**Issue by aj7tesh** [project-anuvaad/OpenNMT-py#19]

**Comment by aj7tesh** [comment]
1.Eng-Gujrati model put to training with initial corpus of 936271(translated using google)

**Comment by VivekRaghavan** [comment]
When do we expect results on this ?

Vivek

**Comment by aj7tesh** [comment]
By tomorrow we will have the model deployed

**Comment by aj7tesh** [comment]
2.English-Bengali

**Comment by aj7tesh** [comment]
3.English-Marathi

**Comment by aj7tesh** [comment]
4.English-Kannada

**Comment by aj7tesh** [comment]
5.English-Telgu

**Comment by aj7tesh** [comment]
> 2.English-Bengali
> Model put to training, 100k steps will be completed in next 66 hours on 1 GPU machine i.e by sunday morning

Model deployed on 16/09/2019. Front end integration remaining

**Comment by aj7tesh** [comment]
> 3.English-Marathi

Model deployed on 16/09/2019. Front end integration remaining

**Comment by aj7tesh** [comment]
Currently, further training is on hold as working on issue number 21.

**Comment by aj7tesh** [comment]
English-Kannada, English-Telgu, English-Malayalam and English-punjabi models have been deployed

**Comment by aj7tesh** [comment]
English-Tamil will be put on training today

**Comment by gauravgola96** [comment]
@aj7tesh  can you please provide a link to download weights?

**Comment by aj7tesh** [comment]
> English-Tamil will be put on training today

Model put to train. Will be deployed by wednesday evening

**Comment by gauravgola96** [comment]
> > English-Tamil will be put on training today
> 
> Model put to train. Will be deployed by wednesday evening

@aj7tesh is there any way to find these models?

**Comment by aj7tesh** [comment]
> > > English-Tamil will be put on training today
> > 
> > 
> > Model put to train. Will be deployed by wednesday evening
> 
> @aj7tesh please provide any way to find these deployed models?

@gauravgola96 Currently the models are server, github doesn't allow to upload big files. I will share s3 in some time then you can access.

**Comment by gauravgola96** [comment]
hey @aj7tesh , 
It would be helpful if you can provide us link to s3 for weights download..
