### ISSUE TITLE
Model messing up the date format

### ISSUE THREAD

**Issue by kumardeepak** [project-anuvaad/OpenNMT-py#4]
It would be awesome if we could get uniform data and time format during the translation

**Comment by aj7tesh** [comment]
Currently,we are able to handle dates, URL when they are sent independently i.e not being part of some sentence in between, but sent as independent tokens. 
Combined formating of date and url is under training in the current tamil model(number 2) being trained. If the experiment succeeds then we shall put it into the english-hindi model.

For now we are following these standards for handling dates (when in individual token):
22.03.1993 - 22.03.1993
22/03/1993 - 22/03/1993
22 March 1993 - 22 मर्च् 1993
22March - 22March
